version: '3'
services: 
  app:
    image: node
    ports:
      - 3000:1883
    command: bash -c 'npm install && npm audit fix && npm start'
    working_dir: /app
    volumes: 
      - .:/app
  db:
    image: mongo
    ports:
      - 27017:27017
    